# Generated by Django 3.2.3 on 2021-06-01 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('employeeID', models.AutoField(primary_key=True, serialize=False)),
                ('account', models.CharField(max_length=50)),
                ('department', models.CharField(max_length=10)),
                ('employeeAddress', models.CharField(max_length=50)),
                ('employeeBirthDate', models.DateField()),
                ('employeeEmail', models.EmailField(max_length=50)),
                ('employeeName', models.CharField(max_length=50)),
                ('employeePhone', models.CharField(max_length=10)),
                ('password', models.CharField(max_length=20)),
            ],
        ),
    ]
