# Generated by Django 3.2.3 on 2021-06-01 13:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cars', '0001_initial'),
        ('trips', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('ticketID', models.AutoField(primary_key=True, serialize=False)),
                ('bookTime', models.TimeField()),
                ('customerName', models.CharField(max_length=20)),
                ('licensePlate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars.car')),
                ('tripID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trips.trip', verbose_name='the related trip')),
            ],
        ),
    ]
